In [12]:
import numpy as np
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import accuracy_score , confusion_matrix
from sklearn.ensemble import GradientBoostingClassifier

### Load Data

In [15]:
data= load_breast_cancer()
X= data.data
y= data.target

### Split the data By StratifiedKFold

In [38]:
SkFsplit = StratifiedKFold(n_splits=5)
#p_rf = np.zeros(y.shape[0])

In [41]:
for n in range(10,100,10):
    
    for train,test in SkFsplit.split(X,y):
        X_train = X[train]
        X_test = X[test]
        y_train = y[train]
        y_test = y[test]
        clf = GradientBoostingClassifier(n_estimators=100, learning_rate=1.0,max_depth=1, random_state=0)
        clf.fit(X_train, y_train)
        y_pred = clf.predict(X_test)
        cm = confusion_matrix(y_test, y_pred)
        print("Confusion matrix for each Fold\n",cm)
        #print(accuracy_score(p_rf,y_test))
    print('score For' ,n , '   '  ,  accuracy_score(y_test , y_pred))

    





Confusion matrix for each Fold
 [[40  3]
 [ 1 71]]
Confusion matrix for each Fold
 [[39  4]
 [ 2 70]]
Confusion matrix for each Fold
 [[41  1]
 [ 0 71]]
Confusion matrix for each Fold
 [[41  1]
 [ 2 69]]
Confusion matrix for each Fold
 [[39  3]
 [ 0 71]]
score For 10     0.9734513274336283
Confusion matrix for each Fold
 [[40  3]
 [ 1 71]]
Confusion matrix for each Fold
 [[39  4]
 [ 2 70]]
Confusion matrix for each Fold
 [[41  1]
 [ 0 71]]
Confusion matrix for each Fold
 [[41  1]
 [ 2 69]]
Confusion matrix for each Fold
 [[39  3]
 [ 0 71]]
score For 20     0.9734513274336283
Confusion matrix for each Fold
 [[40  3]
 [ 1 71]]
Confusion matrix for each Fold
 [[39  4]
 [ 2 70]]
Confusion matrix for each Fold
 [[41  1]
 [ 0 71]]
Confusion matrix for each Fold
 [[41  1]
 [ 2 69]]
Confusion matrix for each Fold
 [[39  3]
 [ 0 71]]
score For 30     0.9734513274336283
Confusion matrix for each Fold
 [[40  3]
 [ 1 71]]
Confusion matrix for each Fold
 [[39  4]
 [ 2 70]]
Confusion matrix for each