In [27]:
# importing required libraries 
import numpy as np 
import matplotlib.pyplot as plt 
import pandas as pd 

In [28]:
# importing or loading the dataset 
dataset = pd.read_csv("D:/csv_files2/Wine.csv")

# distributing the dataset into two components X and Y 
X = dataset.iloc[:, 0:13].values 
y = dataset.iloc[:, 13].values  
dataset.head()

Alcohol  Malic_Acid   Ash  Ash_Alcanity  Magnesium  Total_Phenols  \
0    14.23        1.71  2.43          15.6        127           2.80   
1    13.20        1.78  2.14          11.2        100           2.65   
2    13.16        2.36  2.67          18.6        101           2.80   
3    14.37        1.95  2.50          16.8        113           3.85   
4    13.24        2.59  2.87          21.0        118           2.80   

   Flavanoids  Nonflavanoid_Phenols  Proanthocyanins  Color_Intensity   Hue  \
0        3.06                  0.28             2.29             5.64  1.04   
1        2.76                  0.26             1.28             4.38  1.05   
2        3.24                  0.30             2.81             5.68  1.03   
3        3.49                  0.24             2.18             7.80  0.86   
4        2.69                  0.39             1.82             4.32  1.04   

   OD280  Proline  Customer_Segment  
0   3.92     1065                 1  
1   3.40     1050                 1  
2   3.17     1185                 1  
3   3.45     1480                 1  
4   2.93      735                 1

In [29]:
# Splitting the X and Y into the 
# Training set and Testing set 
from sklearn.model_selection import train_test_split 

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0) 
X_train.shape

(142, 13)

# Scaling Model

In [30]:
from sklearn.preprocessing import StandardScaler
sc= StandardScaler()
X_train= sc.fit_transform(X_train)
X_test= sc.transform(X_test)
print("X train shape",X_train.shape)
print("X test shape",X_test.shape)

X train shape (142, 13)
X test shape (36, 13)


In [31]:
#fit PCA
from sklearn.decomposition import PCA
PCAmodel = PCA(n_components=3,random_state=33)#change number of Components (3,5,7,11)
X_train= PCAmodel.fit_transform(X_train)
X_test = PCAmodel.transform(X_test)
print("X train Shape",X_train.shape)
print("X test shape",X_test.shape)

X train Shape (142, 3)
X test shape (36, 3)


In [32]:
import time
# Fitting Logistic Regression To the training set 
from sklearn.linear_model import LogisticRegression
  
classifier = LogisticRegression(random_state = 0) 
t0= time.time()
classifier.fit(X_train, y_train) 
total_time= time.time()- t0
print("Total time after PCA",total_time)

D:\Anacoda33\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
D:\Anacoda33\lib\site-packages\sklearn\linear_model\logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


Total time after PCA 0.47002696990966797


In [33]:
# Predicting the test set result using  
# predict function under LogisticRegression  
y_pred = classifier.predict(X_test) 
print("y predicted",y_pred[:])
print("y True Values",y_test)
print("Score for Train",classifier.score(X_train,y_train))
print("Score for Test",classifier.score(X_test,y_test))

y predicted [1 3 2 1 2 2 1 3 2 2 3 3 1 2 3 2 1 1 2 1 2 1 1 2 2 2 2 2 2 3 1 1 2 1 1 1]
y True Values [1 3 2 1 2 2 1 3 2 2 3 3 1 2 3 2 1 1 2 1 2 1 1 2 2 2 2 2 2 3 1 1 2 1 1 1]
Score for Train 0.971830985915493
Score for Test 1.0


In [34]:
# making confusion matrix between 
#  test set of Y and predicted value. 
from sklearn.metrics import confusion_matrix ,accuracy_score
  
cm = confusion_matrix(y_test, y_pred) 
print("confusion matrix\n",cm)
print("accuracy_score",accuracy_score(y_pred,y_test))

confusion matrix
 [[14  0  0]
 [ 0 16  0]
 [ 0  0  6]]
accuracy_score 1.0
