In [37]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score,confusion_matrix

Load Data

In [38]:
data= pd.read_csv("D:/csv_files2/Classification/heart.csv")
data.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [39]:
X= data.iloc[:,:-1]
y= data.iloc[:,-1]

In [40]:
scale_data= StandardScaler()
X= scale_data.fit_transform(X)

In [41]:
X_train,X_test,y_train,y_test= train_test_split(X,y,test_size=.25,random_state=42)

In [42]:
Model = RandomForestClassifier(n_estimators=10,criterion='entropy',random_state=33)
Model.fit(X_train,y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='entropy',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=33, verbose=0,
                       warm_start=False)

In [43]:
print("Model train Score",Model.score(X_train,y_train))
print("Model train Score",Model.score(X_test,y_test))
#print("Featurs importance",Model.feature_importances_)

Model train Score 0.9955947136563876
Model train Score 0.8289473684210527


Anthor Way to detect N estimators

In [46]:
for j in range(2,100,10):
   
    classifier = RandomForestClassifier(n_estimators = j, criterion = 'entropy')
    classifier.fit(X_train, y_train)
    
    y_pred = classifier.predict(X_test)
    
    cm = confusion_matrix(y_test, y_pred)
    print('RF for number of Trees : ' , j , ' is : \n' , cm)
    print('The Score is : ',classifier.score(X_test , y_test))
    print('=======================================================')



RF for number of Trees :  2  is : 
 [[33  2]
 [13 28]]
The Score is :  0.8026315789473685
RF for number of Trees :  12  is : 
 [[28  7]
 [ 8 33]]
The Score is :  0.8026315789473685
RF for number of Trees :  22  is : 
 [[29  6]
 [ 8 33]]
The Score is :  0.8157894736842105
RF for number of Trees :  32  is : 
 [[27  8]
 [ 4 37]]
The Score is :  0.8421052631578947
RF for number of Trees :  42  is : 
 [[27  8]
 [ 5 36]]
The Score is :  0.8289473684210527
RF for number of Trees :  52  is : 
 [[28  7]
 [ 6 35]]
The Score is :  0.8289473684210527
RF for number of Trees :  62  is : 
 [[28  7]
 [ 4 37]]
The Score is :  0.8552631578947368
RF for number of Trees :  72  is : 
 [[30  5]
 [ 6 35]]
The Score is :  0.8552631578947368
RF for number of Trees :  82  is : 
 [[27  8]
 [ 5 36]]
The Score is :  0.8289473684210527
RF for number of Trees :  92  is : 
 [[28  7]
 [ 7 34]]
The Score is :  0.8157894736842105
